[package]
name = "microservice-macro"
version = "0.1.0"
authors = ["Kevin Flansburg <kevin.flansburg@gmail.com>"]
edition = "2018"


[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ['full', 'extra-traits'] }
quote = "*"
